# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       harbour-scaler

# >> macros
# << macros

Summary:    Scaler Multi-track Math Synth
Version:    0.1
Release:    1
Group:      Qt/Qt
License:    MIT
BuildArch:  noarch
URL:        https://github.com/poetaster/harbour-scaler
Source0:    %{name}-%{version}.tar.bz2
Requires:   sailfishsilica-qt5 >= 0.10.9
Requires:   libsailfishapp-launcher
Requires:   sailfish-components-webview-qt5

BuildRequires:  qt5-qttools-linguist
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.3
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  desktop-file-utils

%description
Scaler Multi-track Math Synth derived from https://alexcrist.github.io/scaler/

%if "%{?vendor}" == "chum"
PackageName: Scaler
Type: desktop-application
Categories:
 - Game
PackagerName: Mark Washeim (poetaster)
Custom:
 - Repo: https://github.com/poetaster/harbour-scaler
Icon: https://raw.githubusercontent.com/poetaster/harbour-scaler/main/icons/128x128/harbour-scaler.png
Screenshots:
 - https://raw.githubusercontent.com/poetaster/harbour-scaler/main/screen-1.png
 - https://raw.githubusercontent.com/poetaster/harbour-scaler/main/screen-2.png
 - https://raw.githubusercontent.com/poetaster/harbour-scaler/main/screen-3.png
 - https://raw.githubusercontent.com/poetaster/harbour-scaler/main/screen-4.png
%endif

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake5 

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%defattr(0644,root,root,-)
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
# >> files
# << files

